If you ever start pulling in data from external sources or writing web scrapers to gather product information, you will quickly realize that data in the wild is a total mess. Systems crash, fields get left blank, and web pages return weird formats.

Pandas provides incredible tools to clean up this garbage so it doesn't break your backend logic.

## Step 1: The Messy Dataset
Let's create a scraped inventory list that has some serious problems: missing values (NaN - Not a Number) and accidental duplicate entries. Run this code to see the mess:

In [1]:
import pandas as pd

# 'None' will automatically be converted to 'NaN' (missing data) by Pandas
scraped_data = {
    "Item_ID": [101, 102, 103, 101, 104, 105],
    "Product_Name": ["Amul Milk", "Britannia Bread", None, "Amul Milk", "Eggs", "Butter"],
    "Price_INR": [66, 45, 80, 66, None, 58],
    "Stock_Count": [50, 20, 0, 50, 30, None]
}

df_messy = pd.DataFrame(scraped_data)
print("--- ORIGINAL MESSY DATA ---")
print(df_messy)

--- ORIGINAL MESSY DATA ---
   Item_ID     Product_Name  Price_INR  Stock_Count
0      101        Amul Milk       66.0         50.0
1      102  Britannia Bread       45.0         20.0
2      103              NaN       80.0          0.0
3      101        Amul Milk       66.0         50.0
4      104             Eggs        NaN         30.0
5      105           Butter       58.0          NaN

## Step 2: Finding the Problems
Before you fix the data, you need to know where the holes are.

`df.isna().sum()`: This is a lifesaver. It goes through every column and counts exactly how many missing values there are.

`df.duplicated().sum()`: Tells you how many exact duplicate rows exist.

In [2]:
print("\n--- MISSING VALUES COUNT ---")
print(df_messy.isna().sum())

--- MISSING VALUES COUNT ---
Item_ID         0
Product_Name    1
Price_INR       1
Stock_Count     1
dtype: int64

## Step 3: Fixing Missing Data
You basically have two choices when dealing with a missing value: Drop it or Fill it.

### 1. Dropping Data:
If a row is missing crucial information (like the price), you might just want to delete the whole row.

In [18]:
# Drops ANY row that has at least one missing value
df_cleaner = df_messy.dropna() 

# Drops a row ONLY if a specific column is missing data
df_cleaner = df_messy.dropna(subset=['Price_INR'])
df_cleaner

   Item_ID     Product_Name  Price_INR  Stock_Count
0      101        Amul Milk       66.0         50.0
1      102  Britannia Bread       45.0         20.0
2      103  Unknown Product       80.0          0.0
3      101        Amul Milk       66.0         50.0
5      105           Butter       58.0          0.0

### 2. Filling Data
If a product is missing its stock count, deleting the product might be a bad idea. Instead, it is safer to assume the stock is 0.

In [17]:
# Fills missing values in a specific column with a 0
df_cleaner['Stock_Count'] = df_messy['Stock_Count'].fillna(0)

# Fills missing text data
df_cleaner['Product_Name'] = df_messy['Product_Name'].fillna("Unknown Product")
df_cleaner

   Item_ID     Product_Name  Price_INR  Stock_Count
0      101        Amul Milk       66.0         50.0
1      102  Britannia Bread       45.0         20.0
2      103  Unknown Product       80.0          0.0
3      101        Amul Milk       66.0         50.0
5      105           Butter       58.0          0.0

### Step 4: Removing Duplicates
Web scrapers and user forms submit duplicate data all the time. Pandas can wipe them out in one line.

In [20]:
# Keeps the first instance and drops the identical copies
df_unique = df_cleaner.drop_duplicates()
df_unique

   Item_ID     Product_Name  Price_INR  Stock_Count
0      101        Amul Milk       66.0         50.0
1      102  Britannia Bread       45.0         20.0
2      103  Unknown Product       80.0          0.0
5      105           Butter       58.0          0.0

## Your Chapter 4 Exercise
Let's chain these cleaning steps together. Using the df_messy DataFrame provided in Step 1, write a script that does the following three things in order:

- Drop any duplicate rows.
- Fill any missing `Stock_Count` values with 0.
- Drop any rows where the `Price_INR` is missing (because we can't sell an item if we don't know its price).

Print your final, cleaned DataFrame. Give it a shot, and paste your code here when you're ready!

In [24]:
import pandas as pd

scraped_data = {
    "Item_ID": [101, 102, 103, 101, 104, 105],
    "Product_Name": ["Amul Milk", "Britannia Bread", None, "Amul Milk", "Eggs", "Butter"],
    "Price_INR": [66, 45, 80, 66, None, 58],
    "Stock_Count": [50, 20, 0, 50, 30, None]
}

dfe_messy = pd.DataFrame(scraped_data)
dfe_cleaner = dfe_messy.drop_duplicates()

dfe_cleaner["Stock_Count"] = dfe_cleaner["Stock_Count"].fillna(0)
dfe_cleaner = dfe_cleaner.dropna(subset="Price_INR")
print(dfe_cleaner)

   Item_ID     Product_Name  Price_INR  Stock_Count
0      101        Amul Milk       66.0         50.0
1      102  Britannia Bread       45.0         20.0
2      103              NaN       80.0          0.0
5      105           Butter       58.0          0.0