# Chapter 6 - String and Datetime Operations

Let's imagine we are intercepting raw data coming into our API from the user frontend.

In [1]:
import pandas as pd

# Raw data coming from a frontend application
raw_api_data = {
    "search_query": ["  Amul bUtter ", "MAGGI noodles", " tata SALT  ", "eggs  "],
    "order_placed_at": ["2026-03-23 14:05:00", "2026-03-23 14:12:30", "2026-03-23 14:45:00", "2026-03-23 15:00:15"],
    "delivered_at": ["2026-03-23 14:18:00", "2026-03-23 14:30:00", "2026-03-23 14:55:00", "2026-03-23 15:22:00"]
}

df_api = pd.DataFrame(raw_api_data)
print("--- RAW API DATA ---")
df_api

--- RAW API DATA ---

     search_query      order_placed_at         delivered_at
0    Amul bUtter   2026-03-23 14:05:00  2026-03-23 14:18:00
1   MAGGI noodles  2026-03-23 14:12:30  2026-03-23 14:30:00
2     tata SALT    2026-03-23 14:45:00  2026-03-23 14:55:00
3          eggs    2026-03-23 15:00:15  2026-03-23 15:22:00

## 1. String Operations (`.str`)
To clean up text columns in Pandas, you use the `.str` accessor. This unlocks standard Python string methods but applies them to the whole column at once.

Let's clean up those messy search queries by removing the extra spaces (stripping) and making everything lowercase so our database can read it properly.

In [3]:
# Chaining string methods: strip spaces, then make lowercase
df_api['clean_query'] = df_api['search_query'].str.strip().str.capitalize()

print("\n--- CLEANED QUERIES ---")
df_api[['search_query', 'clean_query']]

--- CLEANED QUERIES ---

     search_query    clean_query
0    Amul bUtter     Amul butter
1   MAGGI noodles  Maggi noodles
2     tata SALT        Tata salt
3          eggs             Eggs

## 2. Datetime Operations (`pd.to_datetime` and `.dt`)

If you look at `df_api.info()`, those timestamp columns are just plain text (strings). Pandas doesn't know they are dates yet. We have to convert them

In [5]:
# Convert strings to actual Datetime objects
df_api['order_placed_at'] = pd.to_datetime(df_api['order_placed_at'])
df_api['delivered_at'] = pd.to_datetime(df_api['delivered_at'])
df_api

     search_query     order_placed_at        delivered_at    clean_query
0    Amul bUtter  2026-03-23 14:05:00 2026-03-23 14:18:00    Amul butter
1   MAGGI noodles 2026-03-23 14:12:30 2026-03-23 14:30:00  Maggi noodles
2     tata SALT   2026-03-23 14:45:00 2026-03-23 14:55:00      Tata salt
3          eggs   2026-03-23 15:00:15 2026-03-23 15:22:00           Eggs

Once they are Datetime objects, you can do two magical things:

**A. Time Math**: You can literally subtract them to find out exactly how long a delivery took.

In [7]:
# Calculate delivery duration
df_api['delivery_time'] = df_api['delivered_at'] - df_api['order_placed_at']
df_api

,search_query,order_placed_at,delivered_at,clean_query,delivery_time
0,Amul bUtter,2026-03-23 14:05:00,2026-03-23 14:18:00,Amul butter,0 days 00:13:00
1,MAGGI noodles,2026-03-23 14:12:30,2026-03-23 14:30:00,Maggi noodles,0 days 00:17:30
2,tata SALT,2026-03-23 14:45:00,2026-03-23 14:55:00,Tata salt,0 days 00:10:00
3,eggs,2026-03-23 15:00:15,2026-03-23 15:22:00,Eggs,0 days 00:21:45

**B. Extracting Time Components (`.dt`):** Similar to .str, the .dt accessor lets you pull out specific parts of the date or time.

In [10]:
# Extract just the date, or just the minute the order was placed
df_api['order_date'] = df_api['order_placed_at'].dt.date
df_api['order_minute'] = df_api['order_placed_at'].dt.minute
df_api

,search_query,order_placed_at,delivered_at,clean_query,delivery_time,order_date,order_minute
0,Amul bUtter,2026-03-23 14:05:00,2026-03-23 14:18:00,Amul butter,0 days 00:13:00,2026-03-23,5
1,MAGGI noodles,2026-03-23 14:12:30,2026-03-23 14:30:00,Maggi noodles,0 days 00:17:30,2026-03-23,12
2,tata SALT,2026-03-23 14:45:00,2026-03-23 14:55:00,Tata salt,0 days 00:10:00,2026-03-23,45
3,eggs,2026-03-23 15:00:15,2026-03-23 15:22:00,Eggs,0 days 00:21:45,2026-03-23,0

## Your Chapter 6 Exercise
Let's test your new API data-wrangling skills on the `df_api` DataFrame above.

To analyze peak ordering hours for your quick-commerce platform, you need to isolate the hour of the day each order was placed.

Your Task:

- Make sure you convert the `order_placed_at` column into Datetime objects using `pd.to_datetime()`.

- Create a new column called order_hour.

- Use the .dt accessor to extract just the hour from the order_placed_at column and assign it to your new column.

- Print the DataFrame showing the `clean_query`, `order_placed_at`, and your new `order_hour` column.

In [17]:
dfe_api = pd.DataFrame(raw_api_data)

dfe_api["clean_query"] = df_api.clean_query
dfe_api["order_placed_at"] = pd.to_datetime(dfe_api["order_placed_at"])
dfe_api["order_hour"] = dfe_api["order_placed_at"].dt.hour
dfe_api[["clean_query","order_placed_at","order_hour"]]

     clean_query     order_placed_at  order_hour
0    Amul butter 2026-03-23 14:05:00          14
1  Maggi noodles 2026-03-23 14:12:30          14
2      Tata salt 2026-03-23 14:45:00          14
3           Eggs 2026-03-23 15:00:15          15