# Chapter 3: Selection and Filtering

In [2]:
import pandas as pd

df = pd.read_csv("datasets\\quick_commerce_orders.csv")

## 1. Selecting Columns (Slicing the Data)
Sometimes you don't need the whole table. You just want to isolate one or two specific columns.

Selecting a Single Column:
When you select a single column, Pandas returns it as a Series (1D data). You just pass the column name inside square brackets.

In [3]:
# Let's look at just the items ordered
items = df['Item_Name']
print(items.head())

0          Amul Butter 100g
1    Maggi 2-Minute Noodles
2                 Onion 1kg
3             Tata Salt 1kg
4           Thumbs Up 750ml
Name: Item_Name, dtype: str

### Selecting Multiple Columns:
To select multiple columns, you pass a list of column names. Notice the double square brackets [[ ]]! The inner brackets are the Python list, and the outer brackets are the Pandas selector. This returns a new, smaller DataFrame.

In [4]:
# Creating a streamlined view for the delivery drivers
driver_view = df[['Order_ID', 'Delivery_Time_Min', 'Delivered_On_Time']]
print(driver_view.head())

   Order_ID  Delivery_Time_Min  Delivered_On_Time
0      8001                 12               True
1      8002                 15               True
2      8003                 22              False
3      8004                  9               True
4      8005                 11               True

## 2. Filtering Rows (Conditional Logic)
This is where Pandas shines. You can filter rows based on conditions using a syntax that feels very similar to standard Python, but applied to an entire column at once.

Let's find all the orders that were not delivered on time.

In [16]:
# 1. Create the condition (This creates a Series of True/False values)
late_condition = df['Delivered_On_Time'] == False

# 2. Pass that condition into the DataFrame brackets to filter the rows
late_orders = df[late_condition]

print("--- LATE ORDERS ---")
print(late_orders[['Order_ID', 'Item_Name', 'Delivery_Time_Min']])

df[df['Delivered_On_Time']==False][['Order_ID','Item_Name','Delivery_Time_Min']]

--- LATE ORDERS ---
   Order_ID                  Item_Name  Delivery_Time_Min
2      8003                  Onion 1kg                 22
6      8007  Lays India's Magic Masala                 25

   Order_ID                  Item_Name  Delivery_Time_Min
2      8003                  Onion 1kg                 22
6      8007  Lays India's Magic Masala                 25

> Pro-tip: Most developers write this in a single line like this: late_orders = df[df['Delivered_On_Time'] == False]

## 3. Multiple Conditions (AND / OR)
You can combine conditions to get highly specific data.

Use & for AND (both conditions must be true).

Use | for OR (either condition can be true).
(Note: You must wrap each individual condition in parentheses () when combining them).

Let's find high-value orders (Total Price > ₹100) specifically in the "Dairy" category.

In [18]:
high_value_dairy = df[(df['Total_Price_INR'] > 100) & (df['Category'] == 'Dairy')]

print("--- HIGH VALUE DAIRY ORDERS ---")
high_value_dairy

--- HIGH VALUE DAIRY ORDERS ---

,Order_ID,Order_Date,Item_Name,Category,Quantity,Item_Price_INR,Total_Price_INR,Delivery_Time_Min,Delivered_On_Time
0,8001,2026-03-20,Amul Butter 100g,Dairy,2,58,116,12,True
11,8012,2026-03-23,Amul Taaza Milk 1L,Dairy,3,66,198,13,True

### Your Chapter 3 Exercise
Time to put on your data analyst hat. Imagine you are reviewing inventory movement for the quick-commerce app.

Your Task:
Write a Python script to filter your df to find all orders that meet both of these conditions:

The `Category` is exactly "Snacks"

The `Quantity` ordered is greater than or equal to 3

Once you have filtered the data, print the resulting DataFrame.

In [19]:
df.head()

,Order_ID,Order_Date,Item_Name,Category,Quantity,Item_Price_INR,Total_Price_INR,Delivery_Time_Min,Delivered_On_Time
0,8001,2026-03-20,Amul Butter 100g,Dairy,2,58,116,12,True
1,8002,2026-03-20,Maggi 2-Minute Noodles,Snacks,5,14,70,15,True
2,8003,2026-03-20,Onion 1kg,Produce,1,35,35,22,False
3,8004,2026-03-21,Tata Salt 1kg,Pantry,1,28,28,9,True
4,8005,2026-03-21,Thumbs Up 750ml,Beverages,2,40,80,11,True

In [23]:
snackes_above_equal_3 = df[(df['Category']=="Snacks") & (df['Quantity']>=3)]
snackes_above_equal_3

,Order_ID,Order_Date,Item_Name,Category,Quantity,Item_Price_INR,Total_Price_INR,Delivery_Time_Min,Delivered_On_Time
1,8002,2026-03-20,Maggi 2-Minute Noodles,Snacks,5,14,70,15,True
6,8007,2026-03-22,Lays India's Magic Masala,Snacks,3,20,60,25,False