# Chapter 7 - Aggregation and Grouping

When you build admin dashboards for e-commerce platforms, the business owners don't want to see 50,000 individual orders. They want summaries: "What were the total sales per category today?" or "Which product sold the most units?"

To answer these, we use the most powerful function in Pandas: `.groupby()`.

Under the hood, `.groupby()` uses a logic called Split-Apply-Combine:

1. Split: It breaks your giant table into smaller mini-tables based on a category you choose.
2. Apply: It runs a mathematical function (like sum, mean, or count) on those mini-tables.
3. Combine: It stitches the results back together into a brand new, summarized DataFrame.

## 1. The Dataset

Let's create a solid week of sales data. Copy this into your script:

In [3]:
import pandas as pd

sales_data = {
    "date": ["2026-03-20", "2026-03-20", "2026-03-21", "2026-03-21", "2026-03-22", "2026-03-22"],
    "category": ["Dairy", "Snacks", "Dairy", "Produce", "Snacks", "Dairy"],
    "item": ["Amul Milk", "Lays", "Amul Butter", "Onion 1kg", "Maggi", "Eggs 6pcs"],
    "qty_sold": [10, 5, 4, 12, 20, 8],
    "revenue_inr": [660, 100, 232, 420, 280, 336]
}

df_sales = pd.DataFrame(sales_data)
print("--- RAW SALES DATA ---")
df_sales

--- RAW SALES DATA ---

         date category         item  qty_sold  revenue_inr
0  2026-03-20    Dairy    Amul Milk        10          660
1  2026-03-20   Snacks         Lays         5          100
2  2026-03-21    Dairy  Amul Butter         4          232
3  2026-03-21  Produce    Onion 1kg        12          420
4  2026-03-22   Snacks        Maggi        20          280
5  2026-03-22    Dairy    Eggs 6pcs         8          336

## 2. Basic Grouping (One Category)

Let's say we want to know the total revenue generated by each category.

In [4]:
# 1. Group by the 'category' column
# 2. Select the 'revenue_inr' column to do math on
# 3. Apply the .sum() function
category_revenue = df_sales.groupby('category')['revenue_inr'].sum()

print("\n--- TOTAL REVENUE BY CATEGORY ---")
category_revenue

--- TOTAL REVENUE BY CATEGORY ---

category
Dairy      1228
Produce     420
Snacks      380
Name: revenue_inr, dtype: int64

(Other useful math functions you can apply: `.mean()` for average, `.count()` for the number of rows, `.max()` / `.min()` for highest/lowest).

## 3. Multi-level Indexing (Grouping by Multiple Categories)

You can group by more than one thing at a time by passing a list. Let's find out how much revenue each category made on each specific date.

In [5]:
# Grouping by date FIRST, then by category
daily_category_sales = df_sales.groupby(['date', 'category'])['revenue_inr'].sum()

# .reset_index() flattens the result back into a standard, clean DataFrame
clean_report = daily_category_sales.reset_index()

print("\n--- DAILY REVENUE BY CATEGORY ---")
clean_report

--- DAILY REVENUE BY CATEGORY ---

         date category  revenue_inr
0  2026-03-20    Dairy          660
1  2026-03-20   Snacks          100
2  2026-03-21    Dairy          232
3  2026-03-21  Produce          420
4  2026-03-22    Dairy          336
5  2026-03-22   Snacks          280

### **Your Chapter 7 Exercise**

Imagine the inventory manager for your platform asks you: *"I need to know exactly how many units of each specific item we sold this week so I can restock."*

**Your Task:**
Using the `df_sales` DataFrame:
1.  Group the data by the `item` column.
2.  Calculate the **total sum** of the `qty_sold` for each item.
3.  Assign the result to a variable (e.g., `item_quantities`) and print it.

In [13]:
item_quantities = df_sales.groupby('item')['qty_sold'].sum()
item_quantities

item
Amul Butter     4
Amul Milk      10
Eggs 6pcs       8
Lays            5
Maggi          20
Onion 1kg      12
Name: qty_sold, dtype: int64